### ISSUE TITLE
3rd person Bug

### ISSUE THREAD

**Issue by KrackenLackin** [DevsterGames/SwordsOfGurrahPublic#14]
**Describe the bug**
When loading into a lobby or loading into a new round there is a very small chance to go into 3rd person and it has two different variations: Disconnected and Connected.

Connected is when your arms are connected to the place where you hands should be, your body is in front of you almost, and you are missing your head. 
Disconnected is when your body is free to move but you are stationary and invisible, your head is still there and your hands are behind your back.

The Disconnected version is caused by loading a new match 
The connected version is caused by loading into a new game mode 

**To Reproduce**
No known ways to reproduce it seems like a very rare chance to happen 

**Expected behavior**
i shouldnt be disconnected from my body

**Screenshots and/or Videos**
Connected: https://medal.tv/clips/43957654/d1337zWtgy50
Disconnected: https://medal.tv/clips/52733840/d13377bPPHnO

**Platform:**
 Steam 
 CV1

**Additional context**
ive never seen this happen to anyone else and i haven't found a way to recreate it consistently ive only pulled it off maybe 5 timess

**Comment by benaclejames** [comment]
Hmm, that's very odd. We're working on updating a lot to do with the way the game interacts with steamvr, hopefully this will be fixed in the next update
