### ISSUE TITLE
Weapons Killing after death

### ISSUE THREAD

**Issue by KrackenLackin** [DevsterGames/SwordsOfGurrahPublic#15]
**Describe the bug**
When dying your weapon can fly out of your hand and since it was technically "thrown" it can kill the other duelist even after they won the fight

**To Reproduce**
Get both players low
have them lunge at eachother
and the weapon might get thrown and kill both players 

**Expected behavior**
weapons should not be thrown or do damage after death

**Screenshots and/or Videos**
no video but its very easy to recreate

**Platform:**
Steam
CV1

**Comment by benaclejames** [comment]
This seems intended though. If you were to drop a couple frames before dying, surely it should still count, right?

**Comment by benaclejames** [comment]
After confirming with Devin, this is intended behavior.
